version: "3.7"
services:
  realworld:
    build: .
    environment:
      - DB_URL=jdbc:postgresql://db:5432/postgres
      - DB_USER=root
      - DB_PASS=root
    ports:
      - 8080:8080
      - 8081:8081
    depends_on:
      - db
    volumes:
      - .:/app  # Bind mount the current directory to /app inside the container

  db:
    image: postgres:14.4
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - 5432:5432
